services:
  # SMTP API Application
  smtogo:
    image: ghcr.io/hnrobert/smtogo:latest
    # build:
    #   context: src/
    #   dockerfile: docker/Dockerfile
    container_name: smtogo-api
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
